apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubesync-manager-role
rules:
- apiGroups:
  - jibutech.com.jibutech.com
  resources:
  - kubesyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jibutech.com.jibutech.com
  resources:
  - kubesyncs/finalizers
  verbs:
  - update
- apiGroups:
  - jibutech.com.jibutech.com
  resources:
  - kubesyncs/status
  verbs:
  - get
  - patch
  - update
