apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubesync
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: kubesync
  name: kubesync-leader-election-rolebinding
  namespace: kubesync-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubesync-leader-election-role
subjects:
- kind: ServiceAccount
  name: kubesync-controller-manager
  namespace: kubesync-system
