apiVersion: jibutech.com/v1
kind: KubeSync
metadata:
  name: test
  namespace: qiming-migration
spec:
  dstClusterSecret: cluster1
  nsMap:
    qiming-migration: ys1000
  pause: false
  srcClusterSecret: cluster2
  syncResources:
    - gvr:
        group: migration.yinhestor.com
        resource: droperationrequests
        version: v1
      namespaces:
        - qiming-migration
